version: '3.9'

services:
    app:
        container_name: app
        build:
            context: ./setup
            dockerfile: Dockerfile
            args:
                CURRENT_UNAME: host-user
                CURRENT_GNAME: host-user-group
                CURRENT_UID: 1000
                CURRENT_GID: 1000
        restart: unless-stopped
        tty: true
        working_dir: /code
        volumes:
            - ./src:/code
            - ./output:/output
            - ./build/usr/shared/healthchecks/php-fpm.sh:/usr/shared/healthchecks/php-fpm.sh:ro
        healthcheck:
            test: ["CMD", "/usr/shared/healthchecks/php-fpm.sh"]
            interval: 10s
            timeout: 1s
            retries: 3
