version: '3.9'

volumes:
  caddy_data:
  caddy_config:

services:
    caddy:
        container_name: caddy
        image: caddy:2.7.6-alpine
        restart: unless-stopped
        volumes:
            - caddy_data:/data
            - caddy_config:/config
            - ./build/shared/etc/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./src:/code
        ports:
            - 80:80
            - 443:443
            - 443:443/udp
        depends_on:
            - app
        healthcheck:
            test: [ "CMD", "wget", "--spider", "http://localhost/caddy-health-check" ]
            interval: 10s
            timeout: 1s
            retries: 3
