version: '3.9'

services:
    app:
        container_name: app
        build:
            context: ./setup
            dockerfile: Dockerfile
        restart: unless-stopped
        tty: true
        working_dir: /code
        volumes:
            - ./src:/code
            - ./output:/output
            - ./setup/usr/shared/healthchecks/php-fpm.sh:/usr/shared/healthchecks/php-fpm.sh:ro
        healthcheck:
            test: ["CMD", "/usr/shared/healthchecks/php-fpm.sh"]
            interval: 10s
            timeout: 1s
            retries: 3
