version: '3.9'

services:
    app:
        container_name: app
        build:
            context: .
            dockerfile: Dockerfile
            target: build-development
        restart: unless-stopped
        tty: true
        volumes:
            - ./src:/code
            - ./output:/output
            - ./build/shared/usr/shared/healthchecks/php-fpm.sh:/usr/shared/healthchecks/php-fpm.sh:ro
        healthcheck:
            test: ["CMD", "/usr/shared/healthchecks/php-fpm.sh"]
            interval: 10s
            timeout: 1s
            retries: 3
